[package]
name = "stable-log-lists"
version = "0.0.1"
description = "Linked lists in regions"
repository = "https://github.com/research-ag/stable-log-lists"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.14.13"

[dev-dependencies]
test = "2.0.0"

[toolchain]
moc = "0.14.13"
wasmtime = "34.0.0"
